version: '3.8'

services:
  l9-graphrag:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
      - "9090:9090"  # Metrics
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=graphrag-password
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - LOG_LEVEL=INFO
      - ENABLE_METRICS=true
      - TOKENIZERS_PARALLELISM=false
      # Local cross-encoder reranker configuration
      - RERANKER_MODEL=BAAI/bge-reranker-base
      - RERANKER_MODEL_PATH=/app/models/reranker  # mount or bake model here
      - RERANK_BUDGET_MS=120
      - RERANK_CACHE_TTL=600
    volumes:
      - workspace:/workspace
      - ./config:/app/config
      - models:/app/models  # persist model weights/cache
    depends_on:
      neo4j:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  neo4j:
    image: neo4j:5.22-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/graphrag-password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "graphrag-password", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  qdrant:
    image: qdrant/qdrant:v1.10.0
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Redis for caching and health checks
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Optional: Embedding service for production
  embeddings:
    image: neural-embeddings:latest
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=nomic-embed-text-v1.5
      - BATCH_SIZE=32
      - MAX_LENGTH=2048
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Neural Indexer Sidecar Service
  l9-indexer:
    build:
      context: .
      dockerfile: docker/Dockerfile.indexer
    container_name: l9-neural-indexer
    environment:
      # Service Configuration
      - PROJECT_PATH=/workspace
      - PROJECT_NAME=${PROJECT_NAME:-default}
      - INITIAL_INDEX=true
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # Database Connections
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=graphrag-password
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      
      # Embedding Service
      - EMBEDDING_SERVICE_HOST=embeddings
      - EMBEDDING_SERVICE_PORT=8000
      
      # Performance Tuning
      - BATCH_SIZE=10
      - DEBOUNCE_INTERVAL=2.0
      - MAX_QUEUE_SIZE=1000
      
      # Monitoring
      - ENABLE_METRICS=true
      - METRICS_PORT=8080
      
      # File watching optimization for Docker
      - WATCHDOG_FORCE_POLLING=1
      
    volumes:
      # Project Source (Read-Only)
      - ./:/workspace:ro
      # Persistent State
      - indexer_state:/app/state
      # Configuration
      - ./neural-tools/config:/app/config:ro
      # Logs
      - indexer_logs:/app/logs
      
    ports:
      - "8080:8080"  # Health/Metrics endpoint
      
    depends_on:
      neo4j:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      redis:
        condition: service_healthy
      embeddings:
        condition: service_healthy
        
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
      
    restart: unless-stopped
    
    # Resource Limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"
          
    # Security
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:size=100M,noexec,nosuid,nodev
      - /app/state:size=200M,noexec,nosuid,nodev
      - /app/logs:size=100M,noexec,nosuid,nodev
      
    networks:
      - l9-graphrag-network

  # Optional: Monitoring stack
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  qdrant_data:
  redis_data:
  workspace:
  prometheus_data:
  grafana_data:
  models:
  indexer_state:
    driver: local
  indexer_logs:
    driver: local

networks:
  default:
    name: l9-graphrag-network
