# Prometheus Configuration for Neural Tools Monitoring
# ADR-053: WriteSynchronizationManager Production Monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'neural-tools'
    environment: 'production'

# Alert rules
rule_files:
  - '/etc/prometheus/alerts.yml'

# AlertManager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
      scheme: http
      timeout: 10s

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Neural Tools custom metrics exporter
  - job_name: 'neural-tools'
    static_configs:
      - targets: ['neural-metrics-exporter:9200']
        labels:
          service: 'neural-tools-mcp'
          component: 'metrics-exporter'
    metrics_path: '/metrics'
    scrape_timeout: 10s

  # Neo4j metrics (via exporter)
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j-exporter:9400']
        labels:
          service: 'neo4j'
          database: 'graphrag'
    metrics_path: '/metrics'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'system'
          host: 'docker-host'

  # Qdrant metrics (if available)
  - job_name: 'qdrant'
    static_configs:
      - targets: ['host.docker.internal:46333']
        labels:
          service: 'qdrant'
          database: 'vector'
    metrics_path: '/metrics'
    scrape_timeout: 5s
    # Qdrant might not have native metrics endpoint
    honor_timestamps: true
    scheme: http

  # Redis cache metrics
  - job_name: 'redis-cache'
    static_configs:
      - targets: ['host.docker.internal:46379']
        labels:
          service: 'redis'
          role: 'cache'
    metrics_path: '/metrics'
    scrape_timeout: 5s

  # Indexer service health
  - job_name: 'indexer'
    static_configs:
      - targets: ['host.docker.internal:48080']
        labels:
          service: 'indexer'
          component: 'neural-indexer'
    metrics_path: '/health'
    scrape_timeout: 5s