networks:
  l9-network-claude-l9-template:
    driver: bridge
    name: l9-network-claude-l9-template
services:
  qdrant:
    container_name: l9-qdrant-claude-l9-template
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    environment:
    - QDRANT__SERVICE__HTTP_PORT=6333
    - QDRANT__SERVICE__GRPC_PORT=6334
    - QDRANT__SERVICE__HOST=0.0.0.0
    - QDRANT__LOG_LEVEL=INFO
    - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage
    - QDRANT__STORAGE__SNAPSHOTS_PATH=/qdrant/snapshots
    - QDRANT__STORAGE__WAL__WAL_CAPACITY_MB=32
    - QDRANT__STORAGE__WAL__WAL_SEGMENTS_AHEAD=2
    - QDRANT__STORAGE__PERFORMANCE__INDEXING_THRESHOLD_KB=20000
    - QDRANT__STORAGE__OPTIMIZERS__DEFAULT_SEGMENT_NUMBER=4
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD
      - curl
      - -f
      - http://localhost:6333/health
      timeout: 10s
    image: qdrant/qdrant:v1.10.0
    labels:
      l9.project: claude-l9-template
      l9.project.hash: 6db90dcb
      l9.project.path: /Users/mkr/local-coding/claude-l9-template
      l9.type: qdrant-db
    networks:
    - l9-network-claude-l9-template
    ports:
    - 6678:6333
    - 6679:6334
    restart: unless-stopped
    volumes:
    - ./claude-l9-template_qdrant_storage:/qdrant/storage:z
    - ./claude-l9-template_qdrant_snapshots:/qdrant/snapshots:z
version: '3.8'
